# Generated by Django 3.0.7 on 2020-06-06 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200606_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='title',
        ),
    ]
